"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { cn } from "@/lib/cn";
import { Card } from "@/components/ui/Card";
import { Pill } from "@/components/ui/Pill";
import { Button } from "@/components/ui/Button";
import { PlatformGlyph } from "@/components/ui/PlatformGlyph";
import { api } from "@/lib/api/client";
import { Check, X, Pencil, Eye, Send, AlertTriangle, RefreshCw, Sparkles } from "lucide-react";
import type { Database, PieceStatus } from "@/lib/supabase/types";

type Run = Database["public"]["Tables"]["runs"]["Row"];
type Piece = Database["public"]["Tables"]["pieces"]["Row"];
type Verdict = "approved" | "rejected" | "review";

export function ApproveStep({
  runId,
  demoPieces,
  onPublish,
  onBack,
}: {
  runId: string;
  demoPieces?: unknown[];
  onPublish: () => void;
  onBack: () => void;
}) {
  const [pieces, setPieces] = useState<Piece[]>([]);
  // run metadata not needed in demo mode
  const [, setRun] = useState<Run | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [publishing, setPublishing] = useState(false);

  useEffect(() => {
    let alive = true;
    (async () => {
      try {
        if (demoPieces) {
          // Demo mode — pieces already generated by /api/demo/run
          if (!alive) return;
          setPieces(
            (demoPieces as Piece[]).map((p) => ({
              ...p,
              status:
                p.status === "ready"   ? ("approved" as PieceStatus)
                : p.status === "flagged" ? ("review"   as PieceStatus)
                : p.status === "failed"  ? ("rejected" as PieceStatus)
                : p.status,
            })),
          );
          return;
        }
        const data = await api.get<{ run: Run; pieces: Piece[] }>(`/api/runs/${runId}`);
        if (!alive) return;
        setRun(data.run);
        setPieces(
          data.pieces.map((p) => ({
            ...p,
            status:
              p.status === "ready"   ? ("approved" as PieceStatus)
              : p.status === "flagged" ? ("review"   as PieceStatus)
              : p.status === "failed"  ? ("rejected" as PieceStatus)
              : p.status,
          })),
        );
      } catch (e) {
        if (alive) setError((e as Error).message);
      }
    })();
    return () => {
      alive = false;
    };
  }, [runId, demoPieces]);

  async function setVerdict(pieceId: string, verdict: Verdict) {
    setPieces((prev) =>
      prev.map((p) => (p.id === pieceId ? { ...p, status: verdict as PieceStatus } : p)),
    );
    if (demoPieces) return; // demo mode — no DB
    try {
      await api.patch(`/api/pieces/${pieceId}`, { verdict });
    } catch (e) {
      setError((e as Error).message);
    }
  }

  async function handlePublish() {
    setPublishing(true);
    if (demoPieces) {
      onPublish();
      return;
    }
    try {
      await api.post(`/api/runs/${runId}/publish`);
      onPublish();
    } catch (e) {
      setError((e as Error).message);
      setPublishing(false);
    }
  }

  const counts = {
    approve: pieces.filter((p) => p.status === "approved").length,
    reject:  pieces.filter((p) => p.status === "rejected").length,
    review:  pieces.filter((p) => p.status === "review").length,
  };

  return (
    <div className="space-y-6">
      <div className="rise flex flex-wrap items-end justify-between gap-4">
        <div>
          <h1 className="text-large-title tracking-[-0.022em]">
            Almost there. <span className="text-blue">Approve to publish.</span>
          </h1>
          <p className="mt-2 max-w-[60ch] text-body text-label-secondary">
            {pieces.length} pieces are ready for your eyes. Approve, send back for review, or reject.
          </p>
        </div>
        <div className="flex items-center gap-3">
          <Counter label="Approve" count={counts.approve} tone="green" />
          <Counter label="Review" count={counts.review} tone="orange" />
          <Counter label="Reject" count={counts.reject} tone="red" />
        </div>
      </div>

      {error && (
        <div className="rounded-[14px] border border-red/30 bg-red/8 px-5 py-3 text-[13.5px] font-medium text-red">
          {error}
        </div>
      )}

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {pieces.map((p) => (
          <PieceReviewCard
            key={p.id}
            piece={p}
            verdict={p.status as Verdict}
            onSet={(v) => setVerdict(p.id, v)}
          />
        ))}
      </div>

      <Card className="rise rise-3 sticky bottom-3 flex flex-wrap items-center justify-between gap-4">
        <div className="flex items-center gap-3">
          <span className="grid size-10 place-items-center rounded-full bg-green/14 text-green">
            <Check className="size-5" strokeWidth={2.6} />
          </span>
          <div>
            <p className="text-headline">
              {counts.approve} approved · {counts.reject} rejected · {counts.review} for review
            </p>
            <p className="text-footnote text-label-secondary">
              Approved pieces become published in your library. Phase 5 wires them to a scheduler.
            </p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="ghost" size="lg" onClick={onBack} disabled={publishing}>
            ← Back to brief
          </Button>
          <Button
            variant="primary"
            size="lg"
            onClick={handlePublish}
            disabled={counts.approve === 0 || publishing}
          >
            <Send className="size-4" strokeWidth={2.4} />
            {publishing ? "Publishing…" : `Publish ${counts.approve} piece${counts.approve === 1 ? "" : "s"}`}
          </Button>
        </div>
      </Card>
    </div>
  );
}

function Counter({ label, count, tone }: { label: string; count: number; tone: "green" | "orange" | "red" }) {
  const TONE: Record<string, string> = {
    green: "bg-green/14 text-green",
    orange: "bg-orange/14 text-orange",
    red: "bg-red/14 text-red",
  };
  return (
    <div className={`flex items-baseline gap-1.5 rounded-full px-3 py-1 ${TONE[tone]}`}>
      <span className="text-[14px] font-bold num-tabular">{count}</span>
      <span className="text-[12px] font-semibold">{label}</span>
    </div>
  );
}

function PieceReviewCard({
  piece,
  verdict,
  onSet,
}: {
  piece: Piece;
  verdict: Verdict;
  onSet: (v: Verdict) => void;
}) {
  const isFlaggedSource = !!piece.flag_reason;

  return (
    <article
      className={cn(
        "rise group relative flex flex-col overflow-hidden rounded-[18px] bg-card-grouped shadow-card transition-all",
        verdict === "approved" && !isFlaggedSource && "ring-1 ring-green/40",
        verdict === "rejected" && "opacity-70",
        verdict === "review" && "ring-1 ring-orange/50",
      )}
    >
      <Thumbnail piece={piece} isFlagged={isFlaggedSource} />

      <div className="flex flex-1 flex-col p-4">
        <div className="flex items-start justify-between gap-2">
          <div className="min-w-0">
            <div className="flex items-center gap-2">
              <PlatformGlyph platform={piece.platform} size={20} />
              <span className="text-[12.5px] font-medium capitalize text-label-secondary">
                {piece.format.replace(/_/g, " ")}
              </span>
            </div>
            <p className="mt-1.5 line-clamp-2 text-[14.5px] font-semibold leading-[1.3] tracking-[-0.008em] text-label">
              {piece.title ?? "Untitled"}
            </p>
          </div>
          {isFlaggedSource ? (
            <Pill tone="orange" size="sm" dot>Flagged</Pill>
          ) : (
            <Pill tone="green" size="sm" dot>Ready</Pill>
          )}
        </div>

        <p className="mt-2 line-clamp-2 text-[12.5px] leading-[1.5] text-label-secondary">
          {isFlaggedSource ? piece.flag_reason : piece.excerpt ?? piece.copy?.slice(0, 200)}
        </p>

        <div className="mt-4 flex items-center gap-2">
          <VerdictButton
            tone="green"
            label="Approve"
            icon={<Check className="size-3.5" strokeWidth={2.6} />}
            active={verdict === "approved"}
            onClick={() => onSet("approved")}
            disabled={isFlaggedSource}
          />
          <VerdictButton
            tone="orange"
            label="Review"
            icon={<AlertTriangle className="size-3.5" strokeWidth={2.4} />}
            active={verdict === "review"}
            onClick={() => onSet("review")}
          />
          <VerdictButton
            tone="red"
            label="Reject"
            icon={<X className="size-3.5" strokeWidth={2.4} />}
            active={verdict === "rejected"}
            onClick={() => onSet("rejected")}
          />
        </div>

        <div className="mt-3 flex items-center justify-between border-t border-separator pt-3 text-[11.5px] text-label-tertiary">
          <span className="font-mono">
            {piece.id.slice(0, 8)}
            {piece.cost_cents !== null && (
              <>
                {" · "}
                <span className="num-tabular">${(piece.cost_cents / 100).toFixed(2)}</span>
              </>
            )}
          </span>
          <div className="flex items-center gap-1">
            <Tooltip label="Regenerate">
              <button className="pressable grid size-7 place-items-center rounded-full text-label-secondary hover:bg-fill-quaternary">
                <RefreshCw className="size-3.5" strokeWidth={2.2} />
              </button>
            </Tooltip>
            <Tooltip label="Edit">
              <button className="pressable grid size-7 place-items-center rounded-full text-label-secondary hover:bg-fill-quaternary">
                <Pencil className="size-3.5" strokeWidth={2.2} />
              </button>
            </Tooltip>
            <Tooltip label="Open detail">
              <Link
                href={`/library/${piece.run_id}/${piece.id}`}
                className="pressable grid size-7 place-items-center rounded-full text-blue hover:bg-blue/12"
              >
                <Eye className="size-3.5" strokeWidth={2.2} />
              </Link>
            </Tooltip>
          </div>
        </div>
      </div>
    </article>
  );
}

function VerdictButton({
  tone, label, icon, active, onClick, disabled = false,
}: {
  tone: "green" | "orange" | "red";
  label: string;
  icon: React.ReactNode;
  active: boolean;
  onClick: () => void;
  disabled?: boolean;
}) {
  const ACTIVE: Record<string, string> = {
    green: "bg-green text-white",
    orange: "bg-orange text-white",
    red: "bg-red text-white",
  };
  const REST: Record<string, string> = {
    green: "bg-green/12 text-green hover:bg-green/18",
    orange: "bg-orange/12 text-orange hover:bg-orange/18",
    red: "bg-red/12 text-red hover:bg-red/18",
  };
  return (
    <button
      onClick={onClick}
      disabled={disabled}
      className={cn(
        "pressable inline-flex flex-1 items-center justify-center gap-1.5 rounded-[10px] py-2 text-[12.5px] font-semibold transition-all",
        active ? ACTIVE[tone] : REST[tone],
        disabled && "opacity-40",
      )}
    >
      {icon}
      {label}
    </button>
  );
}

function Tooltip({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <span className="group relative inline-flex">
      {children}
      <span className="pointer-events-none absolute left-1/2 top-full z-10 mt-1 -translate-x-1/2 whitespace-nowrap rounded-[6px] bg-label px-1.5 py-0.5 text-[10.5px] font-medium text-bg-elev opacity-0 shadow-card transition-opacity group-hover:opacity-100">
        {label}
      </span>
    </span>
  );
}

function Thumbnail({ piece, isFlagged }: { piece: Piece; isFlagged: boolean }) {
  if (isFlagged) {
    return (
      <div className="relative aspect-[16/10] overflow-hidden bg-orange/8">
        <div className="absolute inset-0 flex flex-col items-center justify-center px-6 text-center">
          <span className="grid size-10 place-items-center rounded-full bg-orange text-white shadow-card">
            <AlertTriangle className="size-5" strokeWidth={2.4} />
          </span>
          <p className="mt-3 line-clamp-3 text-[13.5px] font-semibold leading-[1.35] text-orange">
            {piece.flag_reason}
          </p>
        </div>
      </div>
    );
  }

  if (piece.format === "carousel") {
    return (
      <div className="relative aspect-[16/10] overflow-hidden bg-gradient-to-br from-pink/30 to-purple/30">
        <div className="absolute inset-0 grid grid-cols-3 gap-1 p-3">
          {[0, 1, 2].map((i) => (
            <div
              key={i}
              className="rounded-[8px] shadow-card"
              style={{
                background:
                  i === 0
                    ? "linear-gradient(135deg, oklch(0.18 0.013 270), oklch(0.10 0.013 270))"
                    : i === 1
                    ? "linear-gradient(135deg, oklch(0.62 0.20 251), oklch(0.49 0.20 280))"
                    : "linear-gradient(135deg, oklch(0.97 0.018 60), oklch(0.94 0.024 60))",
                opacity: i === 0 ? 1 : 0.7,
              }}
            />
          ))}
        </div>
        <div className="absolute right-3 top-3 rounded-full bg-white/85 px-2 py-0.5 text-[10.5px] font-semibold text-pink">
          {Array.isArray(piece.slides) ? `${piece.slides.length} slides` : "carousel"}
        </div>
      </div>
    );
  }

  return (
    <div className="relative aspect-[16/10] overflow-hidden bg-bg">
      <div className="p-5">
        <div className="flex items-center gap-2">
          <PlatformGlyph platform={piece.platform} size={20} />
          <span className="text-[11.5px] font-semibold text-label-secondary">@brand</span>
        </div>
        <p className="mt-2 line-clamp-3 text-[12.5px] leading-[1.45] text-label">
          {piece.copy ?? piece.excerpt ?? piece.title}
        </p>
      </div>
      <div className="absolute right-3 top-3 grid size-7 place-items-center rounded-full bg-blue/12 text-blue">
        <Sparkles className="size-3.5" strokeWidth={2.2} />
      </div>
    </div>
  );
}
